### ISSUE TITLE
Support for Whisparr querying

### ISSUE THREAD

**Issue by mat926** [cross-seed/cross-seed#838] opened 2024-12-12 19:56 UTC
### Does your feature request solve a problem you're facing?

N/A

### Does an existing issue/feature request already exist?

- [X] I've searched far and wide!

### What would you like for cross-seed to do?

Add support for querying Whisparr for the media IDs 

### What are you currently doing, if anything, to solve or work around the issue?

N/A

### Additional comments

N/A

**Comment by ShanaryS** [comment] 2024-12-12 20:01
You're going to need to explain what this is and why it's needed. Right now this ticket is meaningless.

**Comment by mat926** [comment] 2024-12-12 20:12
> You're going to need to explain what this is and why it's needed. Right now this ticket is meaningless.

Whisparr is an *arr manager for adult movies. Cross-seed can query the media IDs from Whisparr and can include that as part of the search query.

**Comment by zakkarry** [comment] 2024-12-13 01:26
So, not using whisparr personally- and feeling like this sort of thing should be included in the original ticket instead of a bunch of `N/A`s and seeing @ShanaryS having asked you for specifics...

What metadata sources does whisparr use, do XXX trackers universally use this metadata source as well? Are there multiple sources used on different trackers? Does whisparr use more than one metadata source like Sonarr/Radarr?

We also don't really _explicitly_ support XXX - although it sort of bleeds into the movies formatting. It can be quite difficult to support it given the broad availability of shit naming in XXX and variety of formats, and seems to be a rather niche use case amongst our user-base generally, especially given the number of trackers I'm personally aware of that support XXX in standardized naming/releasing formats.

Frankly, this ticket is kind of a non-starter for me as it sits, and requires me to do pretty much all of the work with trackers and software I don't use and am not at all familiar with in specifics, for something you added N/A too instead of going into any detail, even when asked.

I don't mean to be harsh about it, but please spend at least 2min and give some details (like myself and @ShanaryS  asked for in our responses) edited into the original post.

If you'd like to discuss this with us as well, we're on our Discord. More than happy to spend some time going over specifics there as well.

**Comment by mat926** [comment] 2024-12-13 03:06
> What metadata sources does whisparr use, do XXX trackers universally use this metadata source as well? Are there multiple sources used on different trackers? Does whisparr use more than one metadata source like Sonarr/Radarr?

Right now the only metadata source it uses is stashdb. Sometimes the metadata can be found on IMDB and TVDB. I've seem some trackers use IMDB for XXX videos. (HDT)  I'm not sure if other trackers use stashdb as well but it seems to be gaining support for a metadata source.

> We also don't really _explicitly_ support XXX - although it sort of bleeds into the movies formatting. It can be quite difficult to support it given the broad availability of shit naming in XXX and variety of formats, and seems to be a rather niche use case amongst our user-base generally, especially given the number of trackers I'm personally aware of that support XXX in standardized naming/releasing formats.

I don't know know if it's outside the scope of cross seed but could it parse the release names from the title? Or there is the stashdb API for getting the metadata information including alternate names and formats.

**Comment by zakkarry** [comment] 2024-12-13 03:38
For IDs, the implementation current sends the entire release name to the corresponding *arr, and the *arr handles parsing everything on our behalf.

The issue really comes down to support on prowlarr/jacketts end. Given that I'm unsure if its possible to use that metadata source and ID with prowlarr or jacket, and not supported in the spec....I don't think we'd be able to use stashdb at all.

**Comment by zakkarry** [comment] 2024-12-13 04:00
Confirmed with prowlarr/jackett dev, there is no support for non-standard metadata tags in queries like stash.

Does whisparr use ID's during a search for non IMDB/TMDB metadata sources? If so can you provide the queries from prowlarr/jackett logs? Because I don't think it's a thing.

**Comment by zakkarry** [comment] 2024-12-13 14:22
Given that you said it uses exclusively stash, and prowlarr doesn't support this as a ID search, I'm closing this as its not possible to integrate via torznab.

**Closed by zakkarry** 2024-12-13 14:22 UTC
Labels: feature, triage
