### ISSUE TITLE
Prowlarr rss scan fails if response takes too long

### ISSUE THREAD

**Issue by KaBankz** [cross-seed/cross-seed#396] opened 2023-03-19 19:01 UTC
Prowlarr rss scans fail for one of my indexers that takes a long time to respond.
Cross seed just spits out `Failed to reach http://prowlarr:9696/2/api`.

I timed the request with curl a couple of times, and it took about 35~40sec to complete on average
```bash
time curl -s "http://prowlarr:9696/2/api?apikey=[REDACTED]" > /dev/null
real	0m35.764s
user	0m0.010s
sys		0m0.033s
```

So is there a way to increase the timeout, so longer requests don't fail?

**Comment by mmgoodnow** [comment] 2023-03-26 17:13
dupe of #386

**Closed by mmgoodnow** 2023-03-26 17:13 UTC
