### ISSUE TITLE
Same release group being detected as different release group

### ISSUE THREAD

**Issue by TechieDylan** [cross-seed/cross-seed#591] opened 2024-02-01 15:50 UTC
As mentioned for this specific case YELLO isn't being picked up as the release group for one of them. Not sure what changes can be made but any help is appreciated. (three examples below)

2024-02-01 04:22:11 verbose: [decide] Only.Murders.in.the.Building.(2021).S03.1080p.DSNP.WEB-DL.10bit.SDR.DDP5.1.x265-YELLO - no match for TorrentLeech torrent Only Murders in the Building (2021) S03 1080p DSNP WEB-DL 10bit SDR DDP 5 1 x265 - YELLO - it has a different release group

2024-02-01 08:32:16 verbose: [decide] Masters.of.the.Air.2024.S01E02.Part.Two.1080p.ATVP.WEB-DL.DDP5.1.HEVC-YELLO.mkv - no match for TorrentLeech torrent Masters of the Air 2024 S01E02 Part Two 1080p ATVP WEB-DL DDP 5 1 Atmos x265 - YELLO - it has a different release group

2024-02-01 08:37:39 verbose: [decide] Percy.Jackson.and.the.Olympians.2023.S01E08.The.Prophecy.Comes.True.1080p.DSNP.WEB-DL.DDP5.1.HEVC-YELLO.mkv - no match for TorrentLeech torrent Percy Jackson and the Olympians 2023 S01E08 The Prophecy Comes True 1080p DSNP WEB-DL DDP 5 1 Atmos x265 - YELLO - it has a different release group

**Comment by bakerboy448** [comment] 2024-02-01 16:13
not a bug `Masters of the Air 2024 S01E02 Part Two 1080p ATVP WEB-DL DDP 5 1 Atmos x265 - YELLO` has no release group

`- XXXXX` is not valid release group formatting

**Comment by TechieDylan** [comment] 2024-02-01 16:34
Understood, can it be an enhancement?

For the groups I tend to go after I find the name of the release on websites mainly have `- XXXX` but the actual file structure is `-XXXX`

**Comment by bakerboy448** [comment] 2024-02-01 16:40
the root cause is you need to bitch to your shitty trackers that are arbitrarily changing the name, breaking standards, and breaking all automation tools that rely on the group

**Comment by TechieDylan** [comment] 2024-02-01 19:30
Understandable I didn't realize there was a global standard people follow, I'm not trying to argue that standard. My only thought was that Sonarr and Radarr both can detect the release group with this variation and that there may have been an improvement to be had in detecting it in cross-seed as well.

If its not allowed that's fine, the issue can be closed. Was just looking improve how it matches.

**Comment by zakkarry** [comment] 2024-02-10 07:51
I've already merged a fix for this to the next version branch. It's currently not in a testing/beta state from my perspective, but it has been addressed.

**Closed by zakkarry** 2024-02-10 07:51 UTC
Labels: bug, search
